---
title: "Explore 2"
author: "Blain Morin"
date: "10/6/2021"
output: html_document
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE}

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, fig.width = 10)

library(tidyverse)
library(haven)
library(MatchIt)
library(plotly)
wide.df =  read_dta("Combined_Sandy_Harvey-Oct-08-2019-wide.dta")
long.df =  read_dta("Combined_Sandy_Harvey-Oct-08-2019-long.dta")

long.df = long.df %>%
  filter(all_outliers == 0)

wide.df = wide.df %>%
  filter(all_outliers == 0) %>%
  mutate(industry_codes = as.factor(industry_codes))


df = long.df %>%
  drop_na(cost_sav) %>%
  drop_na(av_loss) %>%
  mutate(Name_of_Tactic = as.factor(Name_of_Tactic)) %>%
  mutate(recovery_shape = as.factor(recovery_path_Combined)) %>%
  mutate(hurricane = as.factor(hurricane)) %>%
  mutate(bi_dummy_employeescantwork = as.factor(ifelse(bi_employees_unable_to_work > 0, 1, 0))) %>%
  mutate(bi_dummy_employeesmoved = as.factor(ifelse(bi_employees_moved_away > 0 , 1, 0))) %>%
  mutate(bi_dummy_comms = as.factor(ifelse(bi_communications > 0, 1, 0))) %>%
  mutate(bi_dummy_supplychain = as.factor(ifelse(bi_supply_chain > 0, 1, 0))) %>%
  mutate(bi_dummy_powerout = as.factor(ifelse(bi_power_outages > 0 , 1, 0))) %>%
  mutate(bi_dummy_natgas = as.factor(ifelse(bi_natural_gas_outages > 0, 1, 0))) %>%
  mutate(bi_dummy_water = as.factor(ifelse(bi_water_outages > 0, 1, 0))) %>%
  mutate(bi_dummy_transport = as.factor(ifelse(bi_transportation > 0, 1, 0))) %>%
  mutate(log_prop_damage = log(property_damage_estimate + 1)) %>%
  mutate(log_prior_emp = log(employees_prior_hurricane)) %>%
  mutate(vrec = as.factor(vrec)) %>%
  rename(Recovered = Censor) %>%
  mutate(industry_codes = as.factor(industry_codes))

### Get Cost Incurring

df2 = df %>%
  filter(cost_sav > 0) %>%
  mutate(BCR = av_loss / cost_sav + .1) %>%
  mutate(av_loss_blain = av_loss + 1) %>%
  mutate(log_cost_sav = log(cost_sav)) %>%
  mutate(log_av_loss_blain = log(av_loss_blain)) %>%
  mutate(logBCR = log(BCR)) %>%
  filter(BCR < 50000) %>%
  filter(av_loss_blain<1000000) %>%
  filter(cost_sav<1000000)


### Get cost saving

df3 = df %>%
  filter(cost_sav < 0) %>%
  mutate(BCR = av_loss / abs(cost_sav) + .1) %>%
  mutate(av_loss_blain = av_loss + 1) %>%
  mutate(log_cost_sav = log(abs(cost_sav))) %>%
  mutate(log_av_loss_blain = log(av_loss_blain)) %>%
  mutate(logBCR = log(BCR)) %>%
  filter(BCR < 50000)%>%
  filter(av_loss_blain<1000000) %>%
  filter(cost_sav<1000000)

```

```{r}

df4 = df %>%
  group_by(vrec) %>%
  mutate(Total_AvLoss = sum(av_loss)) %>%
  ungroup()



```